enum OrderBy { DATE, PRICE }

//BiteFlags
const VENDOR_TYPE_PARTICULAR = 1 << 0; // 1 DESLOCADO DE 0 - 0001
const VENDOR_TYPE_PROFESSIONAL = 1 << 1; // 1 DESLOCADO DE 1 - 0010

// VENDOR_TYPE_PARTICULAR | VENDOR_TYPE_PROFESSIONAL 0011 - Ou logico
